apiVersion: v1
kind: Service
metadata:
  name: prometheus-ext-lb
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    name: port-9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    name: port-9090
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: "prometheus"
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: dse-metric-dashboards-prometheus-demo
        image: "prom/prometheus:v2.4.3"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "4000Mi"
        ports:
        - containerPort: 9090
          name: port-9090
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
        - name: prometheus-volume
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-volume
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
